### ISSUE TITLE
Japanese translation of your manual and blog posting

### ISSUE THREAD

**Issue by asmrt** [NickAkincilar/Snowflake_Google_Data_Studio_Connector#1]
@NickAkincilar 

Thank you for the nice code and instructions. I am very happy to be able to successfully connect Snowflake and DataStudio.

Can I translate these instructions into Japanese, modify some parts (*) that need to be changed in the procedure, and publish them on my blog? Of course, I will specify that it is a quote from your procedure manual.

※ I found out that some of the procedures need to be changed due to an update of Google Apps Script.

I'm Japanese, but I want to blog about it because I want other Japanese Snowflake users to feel happy with your code.

**Comment by asmrt** [comment]
I'm not good at English, so I'm sorry if this is hard to understand. If you have any questions, please ask.

**Comment by NickAkincilar** [comment]
Yes. no problem. Good luck.

**Comment by asmrt** [comment]
Thanks for answering. I will contact you when the blog is ready.
